Ajout des loisirs sportifs sports
incubateur-ademe/nosgestesclimat pull request #2060
Opened 2023-09-05 13:41 UTC by JuliePouliquen

Fix #1958 

Todo : 

- [ ] Ajouter des sports aux personas
- [ ] Pratiques sportives carbonées ?
- [ ] Traduire les règles
- [ ] Traduire les personas

2023-09-08 10:38 UTC, JuliePouliquen commented
À ce stade on a un truc fonctionnel mais qui somme les empreintes club qui ne sont pas censées s'additionner. To be continued.

2023-09-11 09:11 UTC, JuliePouliquen commented
![image](https://github.com/incubateur-ademe/nosgestesclimat/assets/4005340/bae3770f-136b-4b96-bad3-1698982eefa3)
Rediscuté avec @jeremiecook : passage à une seule question => on demande les sports pratiqués régulièrement (les autres sont mis de côté).

À tous les sportifs : empreinte répartie +

- si sport indiv en extérieur : rien
- si sport en salle / musculation : empreinte fitness
- sinon : empreinte club

2023-09-11 12:05 UTC, JuliePouliquen commented
ÇA MARCHE ! Désolée pour les majuscules, mais j'ai un peu galéré.

2023-09-11 19:35 UTC, JuliePouliquen commented
Pour les appellations : 

Option 1
![image](https://github.com/incubateur-ademe/nosgestesclimat/assets/4005340/c3dec0d2-d458-4004-8131-35fc184b82d9)

Option 2
![image](https://github.com/incubateur-ademe/nosgestesclimat/assets/4005340/b88cac04-d87d-464d-8d03-26e6952eaabe)

2023-09-12 12:38 UTC, JuliePouliquen commented
J'ai ajouté des descriptions qui pour le moment sont ineffectives, mais la liste nous paraît OK à @jeremiecook et moi.

2023-09-12 14:49 UTC, Clemog requested changes

2023-09-12 14:49 UTC, Clemog commented on data/divers/divers . loisirs.publicodes
> +divers . loisirs . sports:
Je me dis que ce serait peut-être plus clair d'avoir des fichiers séparés pour chaque catégorie de loisirs

2023-09-12 14:49 UTC, Clemog commented on data/divers/divers . loisirs.publicodes
> +  formule: empreinte répartie + empreinte club + empreinte fitness + empreinte montagne
```suggestion
  formule:
    somme:
      - empreinte répartie
      - empreinte club
      - empreinte fitness
      - empreinte montagne
```

2023-09-12 14:49 UTC, Clemog commented on data/divers/divers . loisirs.publicodes
> +  titre: Vélo
Cyclisme non ?
Vélo ça fait doublon avec le vélotaf

2023-09-12 14:49 UTC, Clemog commented on data/divers/divers . loisirs.publicodes
> +  icônes: 🚲
```suggestion
  icônes: 🚴‍♀️
```

2023-09-12 14:49 UTC, Clemog commented on data/divers/divers . loisirs.publicodes
> +  unité: jours
```suggestion
  unité: jour
```

2023-09-12 14:49 UTC, Clemog commented on data/divers/divers . loisirs.publicodes
> +  unité: kgCO2e / jour
```suggestion
  unité: kgCO2e/jour
```

2023-09-12 14:49 UTC, Clemog commented on data/divers/divers . loisirs.publicodes
> +        alors: empreinte branche . R93 par hab / proportion pratiquants / proportion pratiquants adhérents * 0.63 * 0.41
Dans la mesure ou ce 0.63 est utilisé à plusieurs endroits, il me semble plus fiable de l'externaliser dans une variable unique pour le changer à un seul endroit si besoin

2023-09-12 14:49 UTC, Clemog commented on data/divers/divers . loisirs.publicodes
> +  par défaut: non
Dans mon navigateur (chrome), l'ordre de éléments dans la mosaïque est l'inverse de l'ordre d'apparition des éléments dans le code, c'est moyen je trouve du coup
Je crois qu'on a déjà eu un souci de ce type précédemment

2023-09-12 14:49 UTC, Clemog commented on data/divers/divers . loisirs.publicodes
> +  note: Nous prenons la moyenne de temps passé aux sports d'hiver pour toute personne cochant la case.
Ajouter l'unité ;)

2023-09-12 14:49 UTC, Clemog commented on data/divers/divers . loisirs.publicodes
> +  note: Nous prenons ici la part concernant la Gestion d'installations sportives (27%) et Autres activités liées au sport (21%) au sein de Activités liées au sport (63%), que l'on multiplie par la pr
Ajouter l'unité ;)

2023-09-12 14:49 UTC, Clemog commented on data/divers/divers . loisirs.publicodes
> +  note: Nous prenons ici la part concernant les Activités de centres de culture physique (11%), répartis sur la proportion de sportifs étant abonné à ce type de centres.
Ajouter l'unité ;)

2023-09-12 14:49 UTC, Clemog commented on data/divers/divers . loisirs.publicodes
> +  note: Nous prenons ici la part concernant les Activités de clubs de sports (41%), répartis sur la proportion de sportifs étant adhérent d'un club de sport.
Ajouter l'unité ;)

2023-09-12 14:53 UTC, Clemog commented on data/divers/divers . loisirs.publicodes
> +    L'un (ou plusieurs) des sports que vous avez coché est susceptible d'avoir une empreinte carbone significativement supérieure aux autres sports.
Je propose un autre début de phrase :

L'un (ou plusieurs) des sports que vous avez coché -> Certains sports (motorisés, nautiques ...)

Comme la notification apparait seulement selon cette condition, l'utilisateur sait qu'il a coché ce type de sport non ?

2023-09-12 15:02 UTC, Clemog commented
Super boulot !

Quelques remarques assez générales en plus de mes commentaires :)

- Côté site, j'ouvre une PR pour corriger l'affichage italique des descriptions 
- L'ordre de la mosaïque n'est pas correctement géré pour moi (chrome) -> j'essaie de voir si je peux le corriger en même temps que le point précédent 
- Je suis dubitatif sur le côté non additionnel de l'empreinte des sports : hors contraintes de données, il me semble pas intuitif que 2 sports c'est une empreinte club 2 fois supérieure ..

2023-09-12 15:06 UTC, Clemog commented on data/divers/divers . loisirs.publicodes
> +        alors: empreinte branche . R93 par hab / proportion pratiquants / proportion pratiquants adhérents * 0.63 * 0.41
Je reviens sur mon premier commentaire à l'a lecture de la doc NGC, je pense que ce serait mieux d'avoir une variable `empreinte par adhérent` ou qque chose comme ça directement qui serait `empreinte branche . R93 par hab * 0.63` ce serait plus compréhensible dans les formules.

2023-09-12 15:10 UTC, Clemog commented on data/divers/divers . loisirs.publicodes
> +        alors: empreinte branche . R93 par hab / proportion abonnés fitness * 0.63 * 0.11
C'est peut etre juste moi mais je serais plus à l'aise avec une écriture avec parenthèses pour mieux lire et être bien sur du calcul

```
((empreinte branche . R93 par hab / proportion abonnés fitness) * 0.63) * 0.11

```

2023-09-14 07:14 UTC, JuliePouliquen commented on data/divers/divers . loisirs.publicodes
> +divers . loisirs . sports:
Ça me va tout à fait, ça rentre dans ma logique de "un fichier, une fonction" #maniaque

2023-09-14 07:14 UTC, JuliePouliquen commented on data/divers/divers . loisirs.publicodes
> +  formule: empreinte répartie + empreinte club + empreinte fitness + empreinte montagne
Je peux faire juste "commit suggestion" ?

2023-09-14 07:16 UTC, JuliePouliquen commented on data/divers/divers . loisirs.publicodes
> +  par défaut: non
Ah merde. Oui ça me rappelle quelque-chose. Les mobilités efficaces peut-être ? Tu te souviens comment on avait réglé ça ?

2023-09-14 09:03 UTC, Clemog commented on data/divers/divers . loisirs.publicodes
> +  par défaut: non
Normalement, avec cette [PR](https://github.com/incubateur-ademe/nosgestesclimat-site/pull/1301), c'est mieux géré :)

2023-09-15 08:44 UTC, JuliePouliquen commented
Zut étrange j'ai ajouté des sports aux personas et je le vois pas encore dans le bilan de l'empreinte qui leur est ajoutée (ci-dessus).

2023-09-25 11:10 UTC, Clemog commented
@JuliePouliquen, c'est bon pour les personas suite à la gestion des conflits sur la branche

2023-09-25 11:21 UTC, Clemog commented
Quelques retours supplémentaires:

- Je pense qu'on manque d'explication, à la fois dans les notes et les descriptions sur l'explication de notre méthode, au niveau des règles `divers . loisirs . sports` pour l'aspect 'général' et au niveau de `divers . loisirs . sports . empreinte sportif` pour décrire spécifiquement ce qu'on compte pour le moment
- J'ai repris un tout petit peu certains éléments du yaml, j'espère ne rien avoir cassé

2023-09-25 11:37 UTC, Clemog requested changes

2023-09-25 11:37 UTC, Clemog commented on data/divers/divers . loisirs . sports.publicodes
> +      - sinon: empreinte par défaut
Je pense qu'une description et/ou note expliquant l'approche ici est importante

2023-09-25 11:37 UTC, Clemog commented on data/divers/divers . loisirs . sports.publicodes
> +      - empreinte montagne
On peut expliquer ici pourquoi on choisit cette répartition et à quoi correspondent les éléments de la somme

2023-09-26 07:45 UTC, Clemog approved these changes

2023-09-26 08:09 UTC, merged