Ajout/modification d'abréviations
incubateur-ademe/nosgestesclimat pull request #2141
Opened 2023-11-02 13:23 UTC by bjlaa

2023-11-02 14:21 UTC, Clemog approved these changes

2023-11-02 14:22 UTC, Clemog commented
Il manque juste la trad @bjlaa ;)

2023-11-02 14:23 UTC, Clemog requested changes
Manque juste la trad :)

2023-11-02 14:23 UTC, Clemog commented
Je peux m'en occuper, je regarde ça tout à l'heure

2023-11-02 14:34 UTC, bjlaa commented
Done ! Dis moi si ça te parait good :)

2023-11-07 10:25 UTC, bjlaa commented
@Clemog ça te parait ok désormais ? :)

2023-11-07 10:44 UTC, Clemog commented
Oui mais il faut attendre https://github.com/incubateur-ademe/nosgestesclimat-site-nextjs/pull/172 pour prendre en compte les changements

2023-11-07 10:52 UTC, EmileRolley commented
> Oui mais il faut attendre https://github.com/incubateur-ademe/nosgestesclimat-site-nextjs/pull/172 pour prendre en compte les changements

Il faudra merge sur `master` du coup.

2023-11-07 11:10 UTC, Clemog commented
Oui oui mais je préfère merger tout sur preprod, tester preprod sur le site et merger ensuite sur master

2023-11-08 15:40 UTC, merged