Nouvelles actions alimentation - NGC-306
incubateur-ademe/nosgestesclimat pull request #2223
Opened 2023-12-14 15:42 UTC by JuliePouliquen

2023-12-20 16:17 UTC, Clemog commented
Je viens de regarder le code très rapidement (pas eu le temps de tester)

- Top pour le "nombre de semaines par an"
- Ce serait pas mal d'ajouter des unités désormais pour les actions aussi (on l'a jamais fait) cf #2242 
- Je crois que les `recalcul` que tu utilises ne sont pas utiles dans les différents cas et je trouve que ça alourdit un peu la syntaxe. La valeur de l'action pourrait être simplement la diff entre ce qui est consommé et la valeur "max" x l'empreinte, c'est plus simple et clair je trouve

2023-12-20 16:43 UTC, Clemog approved these changes

2023-12-20 16:43 UTC, Clemog commented on data/actions/alimentation.publicodes
> +  titre: Diviser par deux sa consommation de viande
Pas chaud ..

2023-12-20 16:43 UTC, Clemog commented on data/actions/alimentation.publicodes
> +# alimentation . réduire viande . max 1 par jour:
Commenté ?

2023-12-20 16:43 UTC, Clemog commented on data/actions/alimentation.publicodes
> +  titre: Diviser par quatre sa consommation de viande
Idem pas chaud

2023-12-20 16:43 UTC, Clemog commented on data/actions/alimentation.publicodes
> +alimentation . réduire café . max 2 par jour . recalcul:
Je pense qu'on peut éviter un recalcul ici

2023-12-20 16:43 UTC, Clemog commented on data/actions/alimentation.publicodes
> +  formule: boisson . chaude - recalcul
Idem, je pense que le recalcul est superflus

2023-12-20 16:43 UTC, Clemog commented on data/actions/alimentation.publicodes
> +  formule: boisson . chaude - recalcul
Idem, recalcul pas nécessaire je pense

2023-12-20 16:43 UTC, Clemog commented on data/actions/alimentation.publicodes
> +alimentation . réduire café . max 2 par jour . recalcul:
On pourrait juste avoir l'empreinte d'une tasse x la diff entre le nombre de tasse consommée et 14

2023-12-21 08:42 UTC, JuliePouliquen commented on data/actions/alimentation.publicodes
> +# alimentation . réduire viande . max 1 par jour:
Pas réussi à le faire, vu qu'il y a deux types de viandes...

2023-12-21 08:51 UTC, JuliePouliquen commented on data/actions/alimentation.publicodes
> +  titre: Diviser par deux sa consommation de viande
Pour le coup, il faut qu'on trouve un truc parce que j'ai déjà eu plusieurs fois le retour qu'il y avait un problème avec ce calcul. Et dans les faits ils ont raison : diviser par deux ne veut pas dire "manger une fois par jour". Le seul cas dans lequel ça marche c'est quand on a 14 plats viande. 
À partir du moment où on en a plus de 7, on peut dire qu'il y a au moins un jour où on mange 2 fois de la viande, mais c'est tout. Il est fort possible que la personne qui a mis 7 ou moins soit déjà à "une seule fois de la viande par jour".

2023-12-21 08:51 UTC, JuliePouliquen commented on data/actions/alimentation.publicodes
> +  titre: Diviser par quatre sa consommation de viande
Et même commentaire :smile:. Je cherche une solution...

2023-12-21 10:04 UTC, JuliePouliquen commented on data/actions/alimentation.publicodes
> +# alimentation . réduire viande . max 1 par jour:
(pareil pour le poisson - ou alors on lui supprime tous ses poissons et on en laisse un dont on choisit le type)

2024-01-03 17:24 UTC, Clemog requested changes
Encore des choses à se valider avant de merge, j'ai fait pas mal de nouvelles modifs donc surement des choses à review

2024-01-03 17:27 UTC, Clemog commented on data/actions/alimentation.publicodes
> +  titre: Diviser par deux sa consommation de viande
C'est aussi pour ça qu'on met "ou le soir" dans la description (qu'on devriat peut etre basculer dans le titre ?) mais pour moi on perd en concret, on retiendra moins "diviser par deux"

2024-01-03 17:28 UTC, Clemog commented on data/actions/alimentation.publicodes
> +  titre: Diviser par deux sa consommation de viande
Une solution serait peut être de transformer la formule avec une différence entre le consommation et 7 repas par semaine

2024-01-03 17:44 UTC, Clemog commented on data/actions/alimentation.publicodes
> +  titre: Diviser par deux sa consommation de viande
Je me dis que sur les actions liées aux repas, on pourrait solliciter un brainstorm avec l'équipe

2024-01-03 17:53 UTC, Clemog commented on data/actions/alimentation.publicodes
> +  titre: Diviser par deux sa consommation de viande
> Une solution serait peut être de transformer la formule avec une différence entre le consommation et 7 repas par semaine

Ah je comprends que ça revient à "Max une fois par jour" en commenraire plus bas ;)

2024-01-08 10:33 UTC, JuliePouliquen commented
> Encore des choses à se valider avant de merge, j'ai fait pas mal de nouvelles modifs donc surement des choses à review

J'ai été voir tes modifs, je crois bien que ça me va ! Vois-tu une solution pour le "max 1 viande / poisson par jour" ? On décide arbitrairement que c'est un "poisson 1 / viande 1" ? Je n'ai pas d'idée de génie qui me soit venue pendant les vacances (on pourrait se dire qu'on garde le même pourcentage de viande 1 / 2 que l'utilisateur⋅ice avait, mais qu'on ramène à 7 repas au lieu de X qui est supérieur à 7, mais ça me semble un peu galère...).

Après il nous reste à arbitrer sur les actions viande justement, et on est bons ?

2024-01-10 14:45 UTC, Clemog commented
J'ai refait qques modifs de clean et ajouter l'action "zéro déchet", qu'en penses-tu ? :)

2024-01-15 15:57 UTC, Clemog commented
Quelques retours à première vue:

- J'ai l'impression qu'on a des soucis d'unité, peut-être qu'en ajoutant l'unité "kgCO2e" au niveau du parent ça se verra mais typiquement `nombre de plats viande - commun . jours par semaine`, c'est pas homogène
- On a toujours pas mal d'occurrences de `réduire viande . par deux` et `réduire viande . par  quatre`, du coup j'imagine que les règles chaînées ne fonctionnent plus, à voir si on retombe sur nos pattes en remplaçant par les nouvelles actions

2024-01-16 08:41 UTC, JuliePouliquen commented
> Quelques retours à première vue:
> 
>     * J'ai l'impression qu'on a des soucis d'unité, peut-être qu'en ajoutant l'unité "kgCO2e" au niveau du parent ça se verra mais typiquement `nombre de plats viande - commun . jours par semaine`, c'est pas homogène
> 
>     * Quand on manipule le nombre de repas au niveau de la condition d'applicabilité, il faut ajouter l'unité, genre `applicable si: nombre de plats viande > 7 repas/semaine` sinon on a une erreur (on compare des repas/semaine à 7 "rien" sinon)

A priori j'ai réglé ça hier. J'ai finalement remis le chiffre dans les comparaisons, ça me paraissait plus simple. En faisant `yarn dev`, je n'ai plus d'erreurs d'unités.

J'ai nettoyé les actions viande qu'on supprime.

2024-01-16 16:49 UTC, Clemog commented
J'ai fait un dernier tour, je te laisse vérifier si ça te convient ?

2024-01-18 10:19 UTC, JuliePouliquen commented
> J'ai fait un dernier tour, je te laisse vérifier si ça te convient ?
> 
> Tu avais vérifier en ligne ce que ça donnait ?

Oui j'avais vérifié, notamment avec les personas qui étaient bien affectés par la PR :).

2024-01-18 10:32 UTC, Clemog commented
Il manque des trads mais sinon oui :)

2024-01-18 10:34 UTC, Clemog commented
Mais en l'état et en testant j'ai l'impression que l'écran action est inutilisable ..

2024-01-18 10:35 UTC, Clemog commented
Et les questions supplémentaires ne s'affichent jamais

2024-01-18 10:59 UTC, JuliePouliquen commented
> Il manque des trads mais sinon oui :)

Aaaaah les trads, toujours les trads !

C'est à cause de nous les bugs de l'écran action tu crois ?

2024-01-18 11:09 UTC, Clemog commented
Nope .. pas à cause de la PR j'ai fait des suggestions mais ça fait longtemps je crois ..

2024-01-18 11:21 UTC, JuliePouliquen commented
> Nope .. pas à cause de la PR j'ai fait des suggestions mais ça fait longtemps je crois ..

OK. Je me suis occupée des trads, normalement c'est bon.

2024-01-18 12:12 UTC, Clemog approved these changes

2024-01-18 13:30 UTC, merged