Quick fixs textuels NGC-1249
incubateur-ademe/nosgestesclimat pull request #2455
Opened 2024-09-30 13:28 UTC by JuliePouliquen

2024-10-01 09:54 UTC, bjlaa approved these changes

2024-10-01 09:58 UTC, bjlaa requested changes
<img width="1440" alt="Capture d’écran 2024-10-01 à 11 58 19" src="https://github.com/user-attachments/assets/03f2af50-bd03-4325-a4b4-fc74b5c95606">

J'ai toujours le label Château d'affiché

2024-10-01 11:26 UTC, JuliePouliquen commented
> <img alt="Capture d’écran 2024-10-01 à 11 58 19" width="1440" src="https://private-user-images.githubusercontent.com/12382534/372413708-03f2af50-bd03-4325-a4b4-fc74b5c95606.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3ODIyODEsIm5iZiI6MTcyNzc4MTk4MSwicGF0aCI6Ii8xMjM4MjUzNC8zNzI0MTM3MDgtMDNmMmFmNTAtYmQwMy00MzI1LWE0YjQtZmM3NGI1Yzk1NjA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDExMjYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MTYzNDEzMjFlODY2MzAyYjZhYTU1Nzc2YTY0MGUzYTlkYTFjNDJmMGZkYzg0Y2QxZTVhZTcyZGQwN2I1MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x-ChLDqAYqn42_ne6SqcBwIbtKY9SywbcF3b2XAkUU0">
> 
> J'ai toujours le label Château d'affiché

Je ne comprends pas : j'ai cherché et je n'ai plus une seule occurence du mot "chateau" dans mon fichier !

2024-10-02 10:19 UTC, bjlaa approved these changes

2024-10-02 10:19 UTC, bjlaa commented on data/logement/vacances.publicodes
> +    château 🏰: 500
Peut-être ajouter une majuscule ici aussi ?

2024-10-02 13:32 UTC, bjlaa commented on data/logement/vacances.publicodes
> +    château 🏰: 500
j'ai fait un commit !

2024-10-02 13:32 UTC, merged