Fix empreinte eau textile - NGC-1723
incubateur-ademe/nosgestesclimat pull request #2465
Opened 2024-10-29 13:53 UTC by JuliePouliquen

2024-12-19 15:13 UTC, Clemog requested changes

2024-12-19 15:13 UTC, Clemog commented on data/divers/textile.publicodes
> +    Se basant sur l’étude Toluna & Harris Interactive pour le Ministère de la Transition Écologique et de la Cohésion des Territoire réalisée en février 2024 sur 1076 personnes, nous pondérerons le f
Possible de mettre le lien de l'étude ?

2024-12-19 15:13 UTC, Clemog commented on data/divers/textile.publicodes
> -    Nous n'avons pas utilisé les données de Base Impact (sauf dans le cas du short) car même si les données correspondent à la moyenne de plusieurs produits, beaucoup ne proviennent que d'une seule e
On a toujours besoin de ce paragraphe pour les données carbone non ?

2024-12-19 15:25 UTC, JuliePouliquen commented on data/divers/textile.publicodes
> -    Nous n'avons pas utilisé les données de Base Impact (sauf dans le cas du short) car même si les données correspondent à la moyenne de plusieurs produits, beaucoup ne proviennent que d'une seule e
J'avais déjà mis à jour une partie des données carbone lors de la dernier version d'Ecobalyse, sur base d'Ecobalyse qui est bien plus à jour que la base Carbone. Et je me dis qu'à terme on ne met que du Ecobalyse (en vrai ça prendrait 30 mn de le faire maintenant...).

2024-12-19 15:26 UTC, JuliePouliquen commented on data/divers/textile.publicodes
> +    Se basant sur l’étude Toluna & Harris Interactive pour le Ministère de la Transition Écologique et de la Cohésion des Territoire réalisée en février 2024 sur 1076 personnes, nous pondérerons le f
Ah yes.

2025-01-06 10:49 UTC, JuliePouliquen commented
Très bien ton dernier commit @Clemog ! Tu penses que c'est bon ? On merge ?

2025-01-06 11:28 UTC, Clemog commented
Oui je pense ! :)

2025-01-06 11:28 UTC, Clemog approved these changes

2025-01-07 09:36 UTC, merged